api-key: <INSERT YOUR  OPENAI API KEY HERE>
azure_api_key: <INSERT YOUR AZURE API KEY HERE>
azure_api_version: 2023-07-01-preview
azure_deployment_name: gpt-35-turbo
azure_deployment_name_eb: text-embedding-ada-002
azure_endpoint: https://xxxx.openai.azure.com/
easy_copy: true
json_mode: false
markdown: true
model: gpt-3.5-turbo
non_interactive: false
proxy: socks5://127.0.0.1:2080
supplier: openai
temperature: 1
use_proxy: false
